name: Build

on:
  push:
    paths-ignore:
    - README.md
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} with Java 11 (${{ matrix.workaround }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        workaround: [NO_CLEANUP, UNSAFE, GC]
    env:
      WORKAROUND: ${{ matrix.workaround }}
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Compile and run (workaround ${{ matrix.workaround }})
      run: java -cp java src/org/trap/RandomAccessFileTrap.java ${{ matrix.workaround }} main.o
